### PR TITLE
Made 'user' in deploy_conf optional

### PR DESCRIPTION
**Pull request by cybuhh**
Made 'user' in deploy_conf optional, added node v8.x.x to travis matrix and version bump.

Deploy is strongly dependent on ssh so it should be possible to allow use system wide or user defined username for connection. This username for connection can be fetched from `ssh -G ...` however this solution is only available on unix based systems.

### CODE REVIEW

**Comment by phra** [comment]
LGTM.

can you please separate the commit that updates travis configuration?

**Comment by cybuhh** [comment]
👍  it's done - in 3 commits now

**Comment by cybuhh** [comment]
@phra ping

**Comment by phra** [comment]
@cybuhh i can't merge the PR on my own.

**Comment by cybuhh** [comment]
🙇

**Comment by vmarchaud** [comment]
Published under pm2-deploy `0.3.6`

**Pull request merged**
