### PR TITLE
feat: pass env to post-deploy

### LINKED ISSUE #102: post-deploy didn't use environment variables
Hi! 
Not sure if bug but.. 

So, there is  "env"  : {  ...   } block in every deploy targets in ecosystem.json but even if something is specified there, it doesn't applied to post-depoy command hook. 

Here is use-case: I have post-deployment scripts, i.e migrations which have to be executed before application is started just after deploy. And this scripts  are using same config system which takes db connection credentials from env variables. 

It would be great if env variables from ecosystem will be injected not only for apps but for all hooks too. 

Thank you and sorry for bad english

### PR DESCRIPTION
**Pull request by phra**
fixes #102

### CODE REVIEW

**Comment by lardissone** [comment]
@vmarchaud it's already merged to pm2? I still can't see the `env` vars from deploy within my app.

**Comment by phra** [comment]
@lardissone can you clone this repository and `npm link` this package in your project to see if it fixes the problem? thanks.

**Comment by lardissone** [comment]
@phra I've linked the repo and seems to work from client side. At least it executes the `post-deploy` with the ENV vars correctly. 

Previously:
```
  ○ executing post-deploy `npm install && pm2 startOrRestart pm2.config.js --env production`
```

After fix:
```
  ○ executing post-deploy `export NODE_ENV=production PORT=8400 JWT_SECRET=[redacted] JWT_EXPIRATION_MINUTES=60 MONGO_URI=[redacted] MONGO_URI_TESTS=[redacted] && npm install && pm2 startOrRestart pm2.config.js --env production`
```

But env vars are still not available within the app on the server.

**Comment by vmarchaud** [comment]
you should use `pm2 startOrReload pm2.config.js --env production --update-env` to tell PM2 to actually pickup the new environment and inject it inside the new processes

**Comment by lardissone** [comment]
@vmarchaud I've added `--update-env` and still no luck trying to access `process.env.JWT_SECRET` for example.

**Comment by phra** [comment]
i will try to debug it..

**Comment by phra** [comment]
@lardissone pls create a new ticket regarding the `--update-env` bug. thanks.

**Pull request merged**
